name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  golang:
    name: Go
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: 1.22

      - name: test
        run: go test -v ./gen/go/...
